package co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantesv2.mappers;

import co.edu.unicauca.informacion_presupuestaria.dominio.models.ReportePorGrupos;
import co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantesv2.DTOAnswer.ReportePorGruposDTORespuesta;
import co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantesv2.DTOPeticion.ReportePorGruposDTOPeticion;

public interface ReportePorGruposMapperInfraestructura {
    ReportePorGrupos mappearDePeticionAReportePorGrupos(ReportePorGruposDTOPeticion reporte);
    ReportePorGruposDTORespuesta mappearDeReportePorGruposARespuesta(ReportePorGrupos reporte);
}

