package co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantes.mappers;

import co.edu.unicauca.informacion_presupuestaria.dominio.models.ProyeccionEstudiante;
import co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantes.DTOAnswer.ProyeccionEstudianteDTORespuesta;
import co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantes.DTOPeticion.ProyeccionEstudianteDTOPeticion;

import java.util.List;

public interface ProyeccionEstudianteMapperInfraestructura {
    ProyeccionEstudiante mappearDePeticionAProyeccionEstudiante(ProyeccionEstudianteDTOPeticion proyeccion);
    ProyeccionEstudianteDTORespuesta mappearDeProyeccionEstudianteARespuesta(ProyeccionEstudiante proyeccion);
    List<ProyeccionEstudianteDTORespuesta> mappearDeListaProyeccionEstudianteARespuesta(List<ProyeccionEstudiante> proyecciones);
}

