package co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantes.mappers;

import co.edu.unicauca.informacion_presupuestaria.dominio.models.ReporteEstudiantes;
import co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantes.DTOAnswer.ReporteProyeccionEstudiantesDTORespuesta;
import co.edu.unicauca.informacion_presupuestaria.infraestructura.input.controllerReporteEstudiantes.DTOPeticion.ReporteProyeccionEstudiantesDTOPeticion;

public interface ReporteProyeccionEstudiantesMapperInfraestructura {
    ReporteEstudiantes mappearDePeticionAReporteProyeccionEstudiantes(ReporteProyeccionEstudiantesDTOPeticion reporte);
    ReporteProyeccionEstudiantesDTORespuesta mappearDeReporteEstudiantesARespuesta(ReporteEstudiantes reporte);
}

